### ISSUE TITLE
When evaluate aesthetic_quality, 'CUDA out of memory' always occur for multiple videos

### ISSUE THREAD

**Issue by Crazy-wu-20** [Vchitect/VBench#40]
When evaluating aesthetic_quality for my own videos, I always get the error 'CUDA out of memory', which leading me not be able to batch test. Is there any problem? And according to my understanding, the model should only load one video at a time. 

Example:
`python evaluate.py     --dimension aesthetic_quality     --videos_path ../test     --mode=custom_input`

The first video can be OK. However, for the third one, `torch.cuda.OutOfMemoryError: CUDA out of memory` would occur.

**Comment by whwdreamsky** [comment]
the same problem. The reason is that the CLIP model prediction does not use batch prediction. When the video is too long, there will be a GPU memory overflow problem. Here is the solution.
1. Set num_frames in the load_video function
2. Use serial or batch size in CLIP feature acquisition. The author is also recommended to optimize this.

**Comment by haoyuhsu** [comment]
I add with `torch.no_grad` to `aesthetic_quality.py` and it worked.

```
with torch.no_grad():
            image_feats = clip_model.encode_image(images).to(torch.float32)
            image_feats = F.normalize(image_feats, dim=-1, p=2)
            aesthetic_scores = aesthetic_model(image_feats).squeeze()
```
